#!/usr/bin/env bash

# Reading "$HOME/.config/st_theme/directory_themes" and applying given dir themes on cd
# The entries can be created via 'D' hotkey in the Theme Picker and look like:
# 1.~$ cat $HOME/.config/st_theme/directory_themes
# /home/joe/repos/lc:darkviolet:0.25



export st_dir_theme
function set_theme {
    test -z "$WINDOWID" && return # not in X or sudo w/o env... 
    local DT mycfg precfg dt dflt_cfg d
    local home="${home:-$HOME}" # can be set to sudo user's home
    d="${1:-"$(pwd)"}/xx"
    DT="$(cat "$home/.config/st_theme/directory_themes" 2>/dev/null)"
    test -z "$DT" && return
    dflt_cfg () {
        local l="/tmp/st/$WINDOWID/config"
        [ -e "$l" ] && echo "$l" || echo "$home/.config/st_theme/default_config"
    }
    while :
    do
        d="$(dirname "$d")"
        [ "$d" == "/" ] || [ -n "$dt" ] && break
        dt="$(echo -e "$DT" | grep "$d:" | head -n 1)"
    done

    [ "x$dt" == "x$st_dir_theme" ] && return
    precfg="/tmp/st/$WINDOWID.pre_dir_theme/config"

    if [ -n "$dt" ]; then
        [ -z "$st_dir_theme" ] && { mkdir -p "/tmp/st/$WINDOWID.pre_dir_theme"; cp "$(dflt_cfg)" "$precfg"; }
        t="$(echo "$dt" | cut -d : -f 2-)"
        st_theme set -f -c "alpha=${t##*:}" -t "${t%%:*}" > /dev/null
    else
        (
            test -e "$precfg" && mv "$precfg" "/tmp/st/$WINDOWID/config"
            source "$(dflt_cfg)"
            st_theme set -f -t "$theme" -c "alpha=$alpha" >/dev/null
        )
    fi
    st_dir_theme="$dt"
}

export -f set_theme

